package projects

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"text/template"

	"github.com/siegg/chauffeur/internal/workspace"
)

// nginxData holds all values required to render a site config template.
type nginxData struct {
	Slug              string
	ServerNames       string // space-separated: "primary.test alias1.test"
	DocumentRoot      string
	FPMSocket         string
	WorkspaceRoot     string
	HTTPPort          string
	HTTPSPort         string
	CertFile          string
	KeyFile           string
	ProxyPort         int
	ReverseProxy      bool
	TryFilesParam     string // "$args" for WordPress, "$query_string" for others
	ClientMaxBodySize string
}

var tmplHTTP = template.Must(template.New("http").Parse(`# Generated by chauf — do not edit manually.
server {
    listen {{.HTTPPort}};
    server_name {{.ServerNames}};

    client_max_body_size {{.ClientMaxBodySize}};

    access_log {{.WorkspaceRoot}}/nginx/logs/{{.Slug}}-access.log;
    error_log  {{.WorkspaceRoot}}/nginx/logs/{{.Slug}}-error.log;

{{if .ReverseProxy}}
    location / {
        proxy_pass http://localhost:{{.ProxyPort}};
        proxy_http_version 1.1;
        proxy_set_header Host $proxy_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
{{else}}
    root {{.DocumentRoot}};
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?{{.TryFilesParam}};
    }

    location ~ \.php$ {
        fastcgi_pass unix:{{.FPMSocket}};
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include {{.WorkspaceRoot}}/nginx/etc/fastcgi_params;
    }
{{end}}

    location ~ /\.ht {
        deny all;
    }
}
`))

var tmplHTTPS = template.Must(template.New("https").Parse(`# Generated by chauf — do not edit manually.
server {
    listen {{.HTTPPort}};
    server_name {{.ServerNames}};
    return 301 https://$host:{{.HTTPSPort}}$request_uri;
}

server {
    listen {{.HTTPSPort}} ssl;
    server_name {{.ServerNames}};

    ssl_certificate     {{.CertFile}};
    ssl_certificate_key {{.KeyFile}};
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    client_max_body_size {{.ClientMaxBodySize}};

    access_log {{.WorkspaceRoot}}/nginx/logs/{{.Slug}}-access.log;
    error_log  {{.WorkspaceRoot}}/nginx/logs/{{.Slug}}-error.log;

{{if .ReverseProxy}}
    location / {
        proxy_pass http://localhost:{{.ProxyPort}};
        proxy_http_version 1.1;
        proxy_set_header Host $proxy_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
{{else}}
    root {{.DocumentRoot}};
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?{{.TryFilesParam}};
    }

    location ~ \.php$ {
        fastcgi_pass unix:{{.FPMSocket}};
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param HTTPS on;
        include {{.WorkspaceRoot}}/nginx/etc/fastcgi_params;
    }
{{end}}

    location ~ /\.ht {
        deny all;
    }
}
`))

// RenderNginxConfig generates the nginx site config content for a project.
func RenderNginxConfig(p *Project, workspaceRoot string, httpPort, httpsPort int) (string, error) {
	docRoot := DocumentRoot(p.Path, p.ProjectType)
	proxyPort := p.ProxyPort
	if proxyPort == 0 {
		proxyPort = DefaultProxyPort
	}
	if proxyPort < 1 || proxyPort > 65535 {
		return "", fmt.Errorf("invalid reverse proxy port: %d", proxyPort)
	}
	tryParam := "$query_string"
	if p.ProjectType == TypeWordPress {
		tryParam = "$args"
	}

	// Determine client_max_body_size: nginx override > PHP post_max_size > fallback
	bodySize := "64M" // safe default
	wcfg := workspace.Load()
	if wcfg.Nginx.UploadMaxSize != "" {
		bodySize = wcfg.Nginx.UploadMaxSize
	} else if phpCfg, ok := wcfg.PHP.Versions[p.PHPVersion]; ok {
		bodySize = phpCfg.PostMaxSize
	}

	data := nginxData{
		Slug:              p.Slug,
		ServerNames:       strings.Join(p.AllDomains(), " "),
		DocumentRoot:      docRoot,
		FPMSocket:         p.FPMSocketPath(workspaceRoot),
		WorkspaceRoot:     workspaceRoot,
		HTTPPort:          strconv.Itoa(httpPort),
		HTTPSPort:         strconv.Itoa(httpsPort),
		CertFile:          filepath.Join(workspaceRoot, "nginx", "certs", p.Domain+".crt"),
		KeyFile:           filepath.Join(workspaceRoot, "nginx", "certs", p.Domain+".key"),
		ProxyPort:         proxyPort,
		ReverseProxy:      p.ProjectType == TypeReverseProxy,
		TryFilesParam:     tryParam,
		ClientMaxBodySize: bodySize,
	}

	var buf bytes.Buffer
	var tmpl *template.Template
	if p.SSL {
		tmpl = tmplHTTPS
	} else {
		tmpl = tmplHTTP
	}
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("render nginx template: %w", err)
	}
	return buf.String(), nil
}

// WriteNginxConfig renders and writes the nginx site config to sites-available.
func WriteNginxConfig(p *Project, workspaceRoot string, httpPort, httpsPort int) error {
	content, err := RenderNginxConfig(p, workspaceRoot, httpPort, httpsPort)
	if err != nil {
		return err
	}

	sitesAvail := filepath.Join(workspaceRoot, "nginx", "etc", "sites-available")
	if err := os.MkdirAll(sitesAvail, 0755); err != nil {
		return fmt.Errorf("create sites-available: %w", err)
	}

	dest := filepath.Join(sitesAvail, p.Slug+".conf")
	return os.WriteFile(dest, []byte(content), 0644)
}

// EnableNginxSite creates the symlink in sites-enabled pointing to sites-available.
func EnableNginxSite(p *Project, workspaceRoot string) error {
	sitesAvail := filepath.Join(workspaceRoot, "nginx", "etc", "sites-available")
	sitesEnabled := filepath.Join(workspaceRoot, "nginx", "etc", "sites-enabled")

	if err := os.MkdirAll(sitesEnabled, 0755); err != nil {
		return fmt.Errorf("create sites-enabled: %w", err)
	}

	link := filepath.Join(sitesEnabled, p.Slug+".conf")
	// Remove stale symlink if present (idempotent re-link)
	_ = os.Remove(link)

	// Use a relative target so the symlink works regardless of workspace path.
	target := filepath.Join("..", "sites-available", p.Slug+".conf")
	_ = sitesAvail // suppress unused warning
	return os.Symlink(target, link)
}

// DisableNginxSite removes the symlink from sites-enabled.
func DisableNginxSite(p *Project, workspaceRoot string) error {
	link := filepath.Join(workspaceRoot, "nginx", "etc", "sites-enabled", p.Slug+".conf")
	err := os.Remove(link)
	if os.IsNotExist(err) {
		return nil
	}
	return err
}

// RemoveNginxConfig deletes the site config from sites-available.
func RemoveNginxConfig(p *Project, workspaceRoot string) error {
	conf := filepath.Join(workspaceRoot, "nginx", "etc", "sites-available", p.Slug+".conf")
	err := os.Remove(conf)
	if os.IsNotExist(err) {
		return nil
	}
	return err
}
