/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContainersBackupRouteImport } from './routes/containers.backup'
import { Route as ContainersIndexRouteImport } from './routes/containers._index'
import { Route as ContainersNameRouteImport } from './routes/containers.$name'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersBackupRoute = ContainersBackupRouteImport.update({
  id: '/containers/backup',
  path: '/containers/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersIndexRoute = ContainersIndexRouteImport.update({
  id: '/containers/_index',
  path: '/containers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersNameRoute = ContainersNameRouteImport.update({
  id: '/containers/$name',
  path: '/containers/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/containers/$name': typeof ContainersNameRoute
  '/containers': typeof ContainersIndexRoute
  '/containers/backup': typeof ContainersBackupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/containers/$name': typeof ContainersNameRoute
  '/containers': typeof ContainersIndexRoute
  '/containers/backup': typeof ContainersBackupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/containers/$name': typeof ContainersNameRoute
  '/containers/_index': typeof ContainersIndexRoute
  '/containers/backup': typeof ContainersBackupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/containers/$name'
    | '/containers'
    | '/containers/backup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/docs' | '/containers/$name' | '/containers' | '/containers/backup'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/containers/$name'
    | '/containers/_index'
    | '/containers/backup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  ContainersNameRoute: typeof ContainersNameRoute
  ContainersIndexRoute: typeof ContainersIndexRoute
  ContainersBackupRoute: typeof ContainersBackupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers/backup': {
      id: '/containers/backup'
      path: '/containers/backup'
      fullPath: '/containers/backup'
      preLoaderRoute: typeof ContainersBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers/_index': {
      id: '/containers/_index'
      path: '/containers'
      fullPath: '/containers'
      preLoaderRoute: typeof ContainersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers/$name': {
      id: '/containers/$name'
      path: '/containers/$name'
      fullPath: '/containers/$name'
      preLoaderRoute: typeof ContainersNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  ContainersNameRoute: ContainersNameRoute,
  ContainersIndexRoute: ContainersIndexRoute,
  ContainersBackupRoute: ContainersBackupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
