package lib

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
)

// SSLCertificateType represents the type of SSL certificate generated
type SSLCertificateType int

const (
	SSLCertificateTypeSelfSigned SSLCertificateType = iota
	SSLCertificateTypeMkcert
)

// CheckMkcertAvailable checks if mkcert is available and installed
func CheckMkcertAvailable() (bool, string) {
	// Check for mkcert in common locations
	mkcertPaths := []string{"mkcert", "/usr/bin/mkcert", "/usr/local/bin/mkcert"}

	for _, path := range mkcertPaths {
		if _, err := exec.LookPath(path); err == nil {
			// Check if mkcert CA is installed
			cmd := exec.Command(path, "-install")
			if err := cmd.Run(); err != nil {
				// mkcert exists but CA not installed - still usable
				return true, path
			}
			return true, path
		}
	}

	return false, ""
}

// IsMkcertCertificate checks if a certificate was generated by mkcert
func IsMkcertCertificate(certPath string) bool {
	cmd := exec.Command("openssl", "x509", "-in", certPath, "-text", "-noout")
	output, err := cmd.CombinedOutput()
	if err != nil {
		return false
	}

	// mkcert certificates contain specific indicators
	certText := string(output)
	return strings.Contains(certText, "mkcert") ||
		   strings.Contains(certText, "FileLevel") ||
		   strings.Contains(certText, "Local") && strings.Contains(certText, "development")
}

// MoveFile moves a file from src to dst
func MoveFile(src, dst string) error {
	if err := os.Rename(src, dst); err != nil {
		// If rename fails, try copy and remove
		if err := copyFile(src, dst); err != nil {
			return err
		}
		return os.Remove(src)
	}
	return nil
}

// copyFile copies a file from src to dst
func copyFile(src, dst string) error {
	data, err := os.ReadFile(src)
	if err != nil {
		return err
	}
	return os.WriteFile(dst, data, 0o644)
}

// RemoveSSLCertificate removes SSL certificate and potentially cleans up trust store
func RemoveSSLCertificate(certPath, keyPath, domain string) (bool, bool, error) {
	// Check if certificate files exist
	certExists := false
	keyExists := false
	if _, err := os.Stat(certPath); err == nil {
		certExists = true
	}
	if _, err := os.Stat(keyPath); err == nil {
		keyExists = true
	}

	if !certExists && !keyExists {
		return false, false, nil
	}

	// Check if this was an mkcert certificate before removing files
	wasMkcert := false
	if certExists {
		wasMkcert = IsMkcertCertificate(certPath)
	}

	// Remove certificate and key files
	var certErr, keyErr error
	if certExists {
		if err := os.Remove(certPath); err != nil {
			certErr = err
		}
	}
	if keyExists {
		if err := os.Remove(keyPath); err != nil {
			keyErr = err
		}
	}

	// Return error if any critical file removal failed
	if certErr != nil || keyErr != nil {
		return certExists, wasMkcert, fmt.Errorf("certificate removal failed (cert: %v, key: %v)", certErr, keyErr)
	}

	return certExists, wasMkcert, nil
}

// CleanupMkcertTrustStore removes mkcert certificates from the system trust store
func CleanupMkcertTrustStore(logger *Logger) error {
	if mkcertAvailable, mkcertCmd := CheckMkcertAvailable(); mkcertAvailable {
		cmd := exec.Command(mkcertCmd, "-uninstall")
		if output, err := cmd.CombinedOutput(); err != nil {
			return fmt.Errorf("failed to remove mkcert certificates from trust store: %v, output: %s", err, string(output))
		}
		return nil
	}
	return fmt.Errorf("mkcert not available")
}